sudo: false
dist: trusty
language: node_js
node_js:
  - node

cache:
  directories:
    - node_modules

branches:
  except:
    - gh-pages
    - fixture
    - /^fixture-tag[0-9]+$/

notifications:
  email:
    on_success: change
    on_failure: always

before_install:
  - npm install -g codecov

script:
  - npm run lint
  - npm run lintspec
  - npm run coverage

after_script:
  - codecov
