sudo: false
dist: trusty
language: node_js
node_js:
  - node

cache:
  directories:
    - node_modules

branches:
  except:
    - gh-pages
    - fixture
    - /^fixture-tag[0-9]+$/

notifications:
  email:
    on_success: change
    on_failure: always

stages:
  - Unit Tests
  - name: Deployment
    if: branch = master

jobs:
  include:

    - stage: Unit Tests
      before_install:
        - gpg --import spec/fixtures/public_key.asc
        - npm install -g codecov
      script:
        - npm run lint
        - npm run lintspec
        - npm run coverage
      after_script:
        - codecov

    - stage: Deployment
      env:
        - secure: ULETW4f6OZubsKtKDTkItLOoboY6SAKdm/u71bTUUNO3Q8HUnvfP0I443vOLr0No6QZ53FvG4O+gaV967XwYqp/xtjVh8KXo3yiOS3mkaQVZl3Ot7rszBrhE6CB36zjR50009KZ8WERK0dW4Ri7m2CLw5m1UA2IB2pzQDnY+SYtZ++OTWCRDZLhHHUKng3ibvHkT77StqHuJdBzKhzLOQaGezLLlM4c7qjmK4PmswsdvbPegn6yrYNq3fIA9Z2cfa04IK9YZHI1e2omb8AVXQ1basvVsaHbVDTfLwTuVY5vXc/MpvEhCehH8Zv/gMjct187StC/BtvSgdQCoLlNKdW3pGphz+A+V8Pz9XyZAZsOpKwDKf4Lhn2iGn7KQWIocZXcNi9rHH9v+9954hC3UIYmp4Ia0rK27t3izGyL+nFXRwRWXk+VQrl/6lOZvuScDfwIs1yztGrOKVU3Ta2iFWF0K3aXucSiVLjYchQbnp3JwA1Xh9FTMfmow4iXMtdnmMv0/ELHkBI3P8tAFQ4rCPfG2JVzknfE/3kuxwBDHD5suJSiMIwTLaSgpn7XP4ITbNirhSH7062BB/HMGpJB/94y7fTBRA32UPPIBA8AzEz4RCKcrLL/D1ZeSVoS0l6YIuYc4+Rt6XeGbsMVKfuMpXzpqdw33UYUudY5F3zmhfbI=
        - secure: TsinpuVavKSC58KF7QzBDIqCJS5mxNyBEZqannYfXq4uml/8Z7Rd2PBDYUpK+jMS7bC+DYdrQ7NsOs7NheOie8JfESpG9DjMhN4Tbt4BMgviIPYiLZfPQTiHBeOiq3Yo5qcOJjz7dcMxgJBm3fflhlw4dojUM7dooScgiejygvGxvgKmv6NJLtTgX5ukjSbFppkaw/VeJtPg9Nd2FPLTPJNyyP9w/GoFTTWmc3PQBMb5Df+WAoKzlHW4Vk9eZpZqHQ2U0RgnL1Uij/sEhbtTBFB6IEfmS8K/fSkSaga5/26oDKSQYbFhHvVnU2iaj7nKRcF5bluDN5ECb8EngLyNPLyXQkaXShNezxvHYyw3J53r8SVgcWC51lYUhipg74lrhSvXg1KmNcpDp7DiUhR5nH/+bbyRLc7tA5ojr87NTWxdhXBcgW0kHinShcY2q5ncDXUW/uYcFxcJ0wXS5V6LzjKQi9RB0hkLWgAR8LPZB/j/1aUGYj5pOV9ItO704noaIK9S0jWdiaXC3r1fSlz4N54oiGVAWFKN/RvDDodWer9TCocf+GcXAzsUa1em20flihf/9YySTOWNz47/bwxsaoD2fZHhXzluaGsJcSdrQY5U2eugBbBtMarR8xlxV+c6fZPudgKDnVvThH3Vi3dEqyD5Mz9dmWVClBM/ye++3o4=
      script:
        - npm run deploy
